### PR TITLE
Extended test coverage to Linux.

### PR DESCRIPTION
**Pull request by felix91gr**
Changed bits on Package.swift and Tests directory, s.t. SPM can make sense of it for Linux.
Tests don't compile yet, but that's coming, I hope.

I need @nicklockwood to test this on Mac OS to make sure I didn't break anything and thus, can move on to let tests compile and run under Linux.

### CODE REVIEW

**Comment by felix91gr** [comment]
Or Travis to run the tests. CI is so nice :)

**Comment by felix91gr** [comment]
This is the output of Travis

image

I guess I didn't think that Travis would be running an XCode command instead of a SPM command. I'll have to rethink the way I changed the order of the files :thinking:

**Comment by felix91gr** [comment]
@nicklockwood what am I missing here? I have no clue as to how xcode testing works. 
I moved the test files into a directory because that's how I learned to use SPM, but I might be totally wrong and that may not be necessary. I'm currently looking into the docs to see how can I make SPM run the tests as they are in `master`, but... I haven't had much success so far >.<

**Comment by nicklockwood** [comment]
@felix91gr apologies for not responding sooner. I don't have a Linux machine to test this on I'm afraid, so I don't know what to suggest.

**Comment by nicklockwood** [comment]
@felix91gr the changes you've made in your fork seem to have borked the Xcode project structure, which is why the tests aren't running. I can fix it, but I suspect it would just be re-broken next time the tests are run.

It's also broken the examples, which may be a side-effect of me including them in the same Xcode project as the package itself. Again, unfortunately I'm not too familiar with SPM so I'll have to read up on it and see if there's a way to restructure the project so it works on Linux and macOS.

**Comment by nicklockwood** [comment]
Fixed in 0.4.0.

**Pull request closed without merging**
